# Generated by Django 4.1.6 on 2023-03-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='target_datetime',
            field=models.DateTimeField(),
        ),
    ]
