# Generated by Django 4.1.6 on 2023-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0005_alter_event_target_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='target_datetime',
            field=models.CharField(max_length=200),
        ),
    ]
