# Generated by Django 4.1.6 on 2023-03-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_passing_score'),
        ('Calendar', '0006_alter_event_target_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.course'),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_datetime',
            field=models.DateTimeField(),
        ),
    ]
