# Generated by Django 4.1.6 on 2023-03-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0007_alter_event_course_alter_event_target_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='mode',
            field=models.CharField(blank=True, choices=[('onsite', 'onsite'), ('online', 'online'), ('hybrid', 'hybrid')], max_length=6),
        ),
    ]
