# Generated by Django 3.2 on 2023-03-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='passing_score',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='perfect_score',
            field=models.IntegerField(default=0),
        ),
    ]
