# Generated by Django 3.2 on 2023-03-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20230305_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='passing_score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
