# Generated by Django 3.2 on 2023-03-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('love', 'Love'), ('angry', 'Angry')], max_length=5),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='tally',
            field=models.IntegerField(default=0),
        ),
    ]
