# Generated by Django 3.2 on 2023-03-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='pub_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='pub_datetime',
            field=models.DateTimeField(),
        ),
    ]
