# Generated by Django 3.2 on 2023-03-06 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20230304_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='forum_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Forum.forumpost'),
            preserve_default=False,
        ),
    ]
