# Generated by Django 3.2 on 2023-05-13 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_reply_forum_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='pub_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 12, 12, 6, 665349)),
        ),
    ]
