# Generated by Django 3.2 on 2023-10-13 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0009_alter_forumpost_pub_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='pub_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 5, 59, 39, 34776)),
        ),
    ]
